#!/usr/bin/env python3
"""
Backfill script for Créditos dashboard columns (migration 042).

Reads pacreditos/scripts/data.json (extracted from Excel by extract_data.py)
and generates SQL UPDATE statements for 3 tables:
  1. rv_units.valor_inmueble          — all units with non-null value
  2. reservations.cuotas_enganche     — units with active reservation
  3. rv_client_profiles               — income_source, prequalification_bank,
                                        is_fha, is_cash_purchase
                                        (units with active reservation + primary client)

NOTE: pipedrive_url is NOT backfilled — Excel only contains "SI" (yes flag),
not actual Pipedrive deal URLs. This field will be populated manually or via
Pipedrive API integration later.

Matching strategy: (project_id, tower_name, unit_number) natural key.

Usage:
    python3 scripts/backfill_creditos.py > scripts/backfill_creditos.sql
"""

from __future__ import annotations

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_JSON = os.path.join(SCRIPT_DIR, "..", "pacreditos", "scripts", "data.json")
OUTPUT_SQL = os.path.join(SCRIPT_DIR, "backfill_creditos.sql")

# DB project IDs (from MEMORY.md)
PROJECT_IDS = {
    "Benestare": "019c7d10-8f5a-74c7-b3df-c2151ad8a376",
    "Bosques Las Tapias": "019c7d10-8ee5-7999-9881-2cd5ad038aa9",
    "Boulevard 5": "019c7d10-8e01-720f-942f-cac0017d83a8",
}

# JSON tower name → DB tower name mapping
# B5 has a single tower named "Principal" in DB but "Boulevard 5" / null in JSON
TOWER_NAME_MAP = {
    ("Boulevard 5", "Boulevard 5"): "Principal",
    ("Boulevard 5", None): "Principal",
}


def db_tower_name(project_name: str, json_tower: str | None) -> str:
    """Map JSON tower name to DB tower name."""
    key = (project_name, json_tower)
    return TOWER_NAME_MAP.get(key, json_tower or "Principal")


def sql_str(val: str | None) -> str:
    """Escape string for SQL."""
    if val is None:
        return "NULL"
    escaped = val.replace("'", "''")
    return f"'{escaped}'"


def unit_subquery(project_id: str, tower_name: str, unit_number: str) -> str:
    """Generate subquery to find rv_units.id by natural key."""
    return (
        f"SELECT ru.id FROM rv_units ru "
        f"JOIN floors f ON f.id = ru.floor_id "
        f"JOIN towers t ON t.id = f.tower_id "
        f"WHERE t.project_id = '{project_id}' "
        f"AND t.name = {sql_str(tower_name)} "
        f"AND ru.unit_number = {sql_str(unit_number)}"
    )


def reservation_subquery(unit_sq: str) -> str:
    """Generate subquery to find the latest active reservation for a unit."""
    return (
        f"SELECT r.id FROM reservations r "
        f"WHERE r.unit_id = ({unit_sq}) "
        f"AND r.status IN ('CONFIRMED', 'PENDING_REVIEW') "
        f"ORDER BY r.created_at DESC LIMIT 1"
    )


def client_subquery(unit_sq: str) -> str:
    """Generate subquery to find the primary client of the latest active reservation."""
    return (
        f"SELECT rc.client_id FROM reservation_clients rc "
        f"JOIN reservations r ON r.id = rc.reservation_id "
        f"WHERE r.unit_id = ({unit_sq}) "
        f"AND r.status IN ('CONFIRMED', 'PENDING_REVIEW') "
        f"AND rc.is_primary = true "
        f"ORDER BY r.created_at DESC LIMIT 1"
    )


def main():
    with open(DATA_JSON, encoding="utf-8") as f:
        data = json.load(f)

    lines: list[str] = []
    lines.append("-- ============================================================================")
    lines.append("-- Backfill: Créditos dashboard columns (migration 042)")
    lines.append(f"-- Source: pacreditos/scripts/data.json (extracted {data.get('extractedAt', 'unknown')})")
    lines.append("-- Generated by: scripts/backfill_creditos.py")
    lines.append("-- ============================================================================")
    lines.append("")

    stats = {
        "valor_inmueble": 0,
        "cuotas_enganche": 0,
        "client_profile": 0,
        "skipped_no_project_id": 0,
        "skipped_disponible_client_fields": 0,
    }

    for project in data["projects"]:
        project_name = project["name"]
        project_id = PROJECT_IDS.get(project_name)
        if not project_id:
            print(f"WARNING: No project ID for '{project_name}', skipping", file=sys.stderr)
            stats["skipped_no_project_id"] += 1
            continue

        lines.append(f"-- {'='*70}")
        lines.append(f"-- {project_name} (project_id: {project_id})")
        lines.append(f"-- {'='*70}")
        lines.append("")

        for tower in project["towers"]:
            tower_name = db_tower_name(project_name, tower["name"])
            lines.append(f"-- --- {tower['name']} → DB tower: {tower_name} ({len(tower['units'])} units) ---")
            lines.append("")

            for unit in tower["units"]:
                apt = unit["apt"]
                usq = unit_subquery(project_id, tower_name, apt)

                # 1. rv_units.valor_inmueble
                vi = unit.get("valorInmueble")
                if vi is not None:
                    lines.append(
                        f"UPDATE rv_units SET valor_inmueble = {vi} "
                        f"WHERE id = ({usq}) AND valor_inmueble IS NULL;"
                    )
                    stats["valor_inmueble"] += 1

                # Skip client/reservation fields for DISPONIBLE units (no reservation in DB)
                if unit["status"] == "DISPONIBLE":
                    has_client_data = any([
                        unit.get("incomeSource"),
                        unit.get("bank"),
                        unit.get("fha"),
                        unit.get("contado"),
                        unit.get("cuotasEnganche"),
                    ])
                    if has_client_data:
                        stats["skipped_disponible_client_fields"] += 1
                    continue

                # 2. reservations.cuotas_enganche
                ce = unit.get("cuotasEnganche")
                if ce is not None:
                    rsq = reservation_subquery(usq)
                    lines.append(
                        f"UPDATE reservations SET cuotas_enganche = {ce} "
                        f"WHERE id = ({rsq}) AND cuotas_enganche IS NULL;"
                    )
                    stats["cuotas_enganche"] += 1

                # 3. rv_client_profiles (income_source, prequalification_bank, is_fha, is_cash_purchase)
                income = unit.get("incomeSource")
                bank = unit.get("bank")
                fha = unit.get("fha", False)
                contado = unit.get("contado", False)

                has_profile_data = income or bank or fha or contado
                if has_profile_data:
                    csq = client_subquery(usq)
                    set_clauses = []
                    if income:
                        set_clauses.append(f"income_source = {sql_str(income)}")
                    if bank:
                        set_clauses.append(f"prequalification_bank = {sql_str(bank)}")
                    if fha:
                        set_clauses.append("is_fha = true")
                    if contado:
                        set_clauses.append("is_cash_purchase = true")

                    # Only update if at least one field has data
                    lines.append(
                        f"UPDATE rv_client_profiles SET {', '.join(set_clauses)} "
                        f"WHERE client_id = ({csq}) "
                        f"AND income_source IS NULL AND prequalification_bank IS NULL;"
                    )
                    stats["client_profile"] += 1

            lines.append("")

    lines.append("-- ============================================================================")
    lines.append("-- SUMMARY")
    lines.append(f"--   valor_inmueble UPDATEs:    {stats['valor_inmueble']}")
    lines.append(f"--   cuotas_enganche UPDATEs:   {stats['cuotas_enganche']}")
    lines.append(f"--   client_profile UPDATEs:    {stats['client_profile']}")
    lines.append(f"--   skipped (DISPONIBLE):      {stats['skipped_disponible_client_fields']}")
    lines.append("-- ============================================================================")
    lines.append("")

    sql = "\n".join(lines)

    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Generated {OUTPUT_SQL}", file=sys.stderr)
    print(f"  valor_inmueble UPDATEs:    {stats['valor_inmueble']}", file=sys.stderr)
    print(f"  cuotas_enganche UPDATEs:   {stats['cuotas_enganche']}", file=sys.stderr)
    print(f"  client_profile UPDATEs:    {stats['client_profile']}", file=sys.stderr)
    print(f"  skipped (DISPONIBLE w/ client data): {stats['skipped_disponible_client_fields']}", file=sys.stderr)


if __name__ == "__main__":
    main()
